# Generated by Django 5.2.1 on 2025-05-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='choice_response',
        ),
        migrations.AddField(
            model_name='response',
            name='choice_response',
            field=models.ManyToManyField(blank=True, to='survey_app.choice'),
        ),
    ]
